export const modules = [
  {
    num: '01',
    path: '/compiler',
    title: 'React Compiler',
    tag: '编译优化',
    detail: '筛选、排序、收藏与商品对比。',
    tone: 'mint',
  },
  {
    num: '02',
    path: '/rsc',
    title: 'Server Components',
    tag: '服务端渲染',
    detail: 'URL 筛选与独立流式区域。',
    tone: 'blue',
  },
  {
    num: '03',
    path: '/actions',
    title: 'Server Actions',
    tag: '数据变更',
    detail: '便签、附件工单与状态流转。',
    tone: 'orange',
  },
  {
    num: '04',
    path: '/hooks',
    title: '异步 Hooks',
    tag: '交互状态',
    detail: '字段校验与失败回退。',
    tone: 'pink',
  },
  {
    num: '05',
    path: '/concurrent',
    title: '并发渲染',
    tag: '响应优先级',
    detail: '多维筛选、统计与分页。',
    tone: 'violet',
  },
  {
    num: '06',
    path: '/store',
    title: 'Zustand 状态管理',
    tag: '共享状态',
    detail: '跨路由学习清单。',
    tone: 'yellow',
  },
  {
    num: '07',
    path: '/web-components',
    title: 'Web Components',
    tag: '组件互操作',
    detail: 'Lit 组件、属性、事件与样式契约。',
    tone: 'blue',
  },
  {
    num: '08',
    path: '/wasm/image',
    title: 'WASM 图片处理',
    tag: '像素运算',
    detail: '上传、滤镜与 PNG 导出。',
    tone: 'mint',
  },
  {
    num: '09',
    path: '/wasm/audio',
    title: 'WASM 音频编解码',
    tag: 'μ-law',
    detail: '压缩、还原、波形与播放。',
    tone: 'orange',
  },
  {
    num: '10',
    path: '/wasm/ai',
    title: 'WASM 本地 AI',
    tag: '模型推理',
    detail: '本地训练与设备异常分类。',
    tone: 'blue',
  },
  {
    num: '11',
    path: '/wasm/fractal',
    title: 'WASM 计算可视化',
    tag: 'Worker + Canvas',
    detail: '缩放分形并观察计算耗时。',
    tone: 'violet',
  },
  {
    num: '12',
    path: '/wasm/runtime',
    title: 'WASM GC 与 WASI',
    tag: '运行时',
    detail: '能力检测与组件模型边界。',
    tone: 'pink',
  },
];
