export const products = [
  {
    id: 'keyboard',
    name: '无线机械键盘',
    category: '设备',
    price: 699,
    rating: 4.8,
    stock: 16,
  },
  {
    id: 'react-book',
    name: 'React 19 实战手册',
    category: '图书',
    price: 89,
    rating: 4.9,
    stock: 42,
  },
  {
    id: 'design-course',
    name: '设计系统工作坊',
    category: '课程',
    price: 299,
    rating: 4.7,
    stock: 8,
  },
  {
    id: 'mouse',
    name: '人体工学鼠标',
    category: '设备',
    price: 359,
    rating: 4.5,
    stock: 0,
  },
  {
    id: 'typescript-book',
    name: 'TypeScript 进阶',
    category: '图书',
    price: 108,
    rating: 4.6,
    stock: 28,
  },
  {
    id: 'performance-course',
    name: '前端性能优化课',
    category: '课程',
    price: 399,
    rating: 4.9,
    stock: 12,
  },
  {
    id: 'monitor',
    name: '27 英寸 4K 显示器',
    category: '设备',
    price: 1199,
    rating: 4.7,
    stock: 5,
  },
  {
    id: 'testing-book',
    name: '组件测试指南',
    category: '图书',
    price: 76,
    rating: 4.4,
    stock: 0,
  },
  {
    id: 'rsc-course',
    name: 'RSC 架构训练营',
    category: '课程',
    price: 599,
    rating: 4.8,
    stock: 6,
  },
  {
    id: 'dock',
    name: 'USB-C 扩展坞',
    category: '设备',
    price: 249,
    rating: 4.3,
    stock: 23,
  },
  {
    id: 'css-book',
    name: '现代 CSS 布局',
    category: '图书',
    price: 92,
    rating: 4.8,
    stock: 31,
  },
  {
    id: 'compiler-course',
    name: 'React Compiler 深入实践',
    category: '课程',
    price: 459,
    rating: 4.6,
    stock: 0,
  },
] as const;

export type Product = (typeof products)[number];
