export const products = [
  {
    id: 'keyboard',
    name: '无线机械键盘',
    category: '设备',
    price: 699,
    rating: 4.8,
    stock: 16,
  },
  {
    id: 'react-book',
    name: 'React 19 实战手册',
    category: '图书',
    price: 89,
    rating: 4.9,
    stock: 42,
  },
  {
    id: 'design-course',
    name: '设计系统工作坊',
    category: '课程',
    price: 299,
    rating: 4.7,
    stock: 8,
  },
  {
    id: 'mouse',
    name: '人体工学鼠标',
    category: '设备',
    price: 359,
    rating: 4.5,
    stock: 0,
  },
  {
    id: 'typescript-book',
    name: 'TypeScript 进阶',
    category: '图书',
    price: 108,
    rating: 4.6,
    stock: 28,
  },
  {
    id: 'performance-course',
    name: '前端性能优化课',
    category: '课程',
    price: 399,
    rating: 4.9,
    stock: 12,
  },
  {
    id: 'monitor',
    name: '27 英寸 4K 显示器',
    category: '设备',
    price: 1199,
    rating: 4.7,
    stock: 5,
  },
  {
    id: 'testing-book',
    name: '组件测试指南',
    category: '图书',
    price: 76,
    rating: 4.4,
    stock: 0,
  },
  {
    id: 'rsc-course',
    name: 'RSC 架构训练营',
    category: '课程',
    price: 599,
    rating: 4.8,
    stock: 6,
  },
  {
    id: 'dock',
    name: 'USB-C 扩展坞',
    category: '设备',
    price: 249,
    rating: 4.3,
    stock: 23,
  },
  {
    id: 'css-book',
    name: '现代 CSS 布局',
    category: '图书',
    price: 92,
    rating: 4.8,
    stock: 31,
  },
  {
    id: 'compiler-course',
    name: 'React Compiler 深入实践',
    category: '课程',
    price: 459,
    rating: 4.6,
    stock: 0,
  },
  {
    id: 'headphones',
    name: '无线降噪耳机',
    category: '设备',
    price: 1499,
    rating: 4.7,
    stock: 14,
  },
  {
    id: 'fullstack-course',
    name: '全栈项目实战营',
    category: '课程',
    price: 1899,
    rating: 4.8,
    stock: 9,
  },
  {
    id: 'office-chair',
    name: '人体工学办公椅',
    category: '设备',
    price: 2399,
    rating: 4.6,
    stock: 7,
  },
  {
    id: 'ultrawide-monitor',
    name: '34 英寸超宽显示器',
    category: '设备',
    price: 2999,
    rating: 4.9,
    stock: 4,
  },
  {
    id: 'advanced-course',
    name: '前端架构进阶课程',
    category: '课程',
    price: 3499,
    rating: 4.7,
    stock: 6,
  },
  {
    id: 'desktop',
    name: '迷你开发主机',
    category: '设备',
    price: 4299,
    rating: 4.8,
    stock: 3,
  },
  {
    id: 'laptop',
    name: '轻薄开发笔记本',
    category: '设备',
    price: 4999,
    rating: 4.9,
    stock: 2,
  },
  {
    id: 'accessibility-book',
    name: 'Web 无障碍设计指南',
    category: '图书',
    price: 129,
    rating: 4.7,
    stock: 24,
  },
  {
    id: 'architecture-book',
    name: '前端架构实践',
    category: '图书',
    price: 168,
    rating: 4.8,
    stock: 18,
  },
  {
    id: 'webcam',
    name: '高清会议摄像头',
    category: '设备',
    price: 549,
    rating: 4.5,
    stock: 20,
  },
  {
    id: 'testing-course',
    name: '自动化测试实战课',
    category: '课程',
    price: 849,
    rating: 4.8,
    stock: 11,
  },
  {
    id: 'microphone',
    name: '桌面 USB 麦克风',
    category: '设备',
    price: 999,
    rating: 4.6,
    stock: 15,
  },
  {
    id: 'react-course',
    name: 'React 项目进阶课',
    category: '课程',
    price: 1299,
    rating: 4.9,
    stock: 10,
  },
  {
    id: 'tablet',
    name: '便携绘图板',
    category: '设备',
    price: 1399,
    rating: 4.6,
    stock: 8,
  },
  {
    id: 'desk-lamp',
    name: '护眼智能台灯',
    category: '设备',
    price: 1699,
    rating: 4.7,
    stock: 13,
  },
  {
    id: 'portable-monitor',
    name: '便携外接显示器',
    category: '设备',
    price: 2099,
    rating: 4.6,
    stock: 9,
  },
  {
    id: 'cloud-course',
    name: '云原生应用实战营',
    category: '课程',
    price: 2299,
    rating: 4.8,
    stock: 5,
  },
  {
    id: 'standing-desk',
    name: '电动升降桌',
    category: '设备',
    price: 2699,
    rating: 4.7,
    stock: 6,
  },
  {
    id: 'design-bootcamp',
    name: '产品设计训练营',
    category: '课程',
    price: 2799,
    rating: 4.9,
    stock: 7,
  },
  {
    id: 'mechanical-keyboard-pro',
    name: '客制化机械键盘套装',
    category: '设备',
    price: 3199,
    rating: 4.8,
    stock: 4,
  },
  {
    id: 'data-course',
    name: '数据可视化专项课',
    category: '课程',
    price: 3699,
    rating: 4.7,
    stock: 6,
  },
  {
    id: 'high-refresh-monitor',
    name: '32 英寸高刷显示器',
    category: '设备',
    price: 3899,
    rating: 4.8,
    stock: 5,
  },
  {
    id: 'camera',
    name: '直播创作相机',
    category: '设备',
    price: 4499,
    rating: 4.6,
    stock: 3,
  },
  {
    id: 'engineering-bootcamp',
    name: '高级工程师训练营',
    category: '课程',
    price: 4599,
    rating: 4.9,
    stock: 8,
  },
  {
    id: 'workstation',
    name: '紧凑型工作站',
    category: '设备',
    price: 4799,
    rating: 4.8,
    stock: 2,
  },
] as const;

export type Product = (typeof products)[number];
